apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  rules:
  - http:
      paths:
      # 1. USER MANAGER
      - path: /user-manager(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: user-manager
            port:
              number: 5000
      
      # 2. DATA COLLECTOR (Default)
      - path: /data-collector(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: data-collector
            port:
              number: 5000
      - path: /sla-detector(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: sla-breach-detector
            port:
              number: 5000