metrics:
  - name: "db_update_slow_data_collector"
    query: "flight_db_update_duration_seconds"
    min: 0
    max: 10.0
  - name: "cpu_usage_high_data_collector"
    query: "data_collector_cpu_usage_percent"
    min: 0
    max: 10
  - name: "db_update_slow_user_manager"
    query: "user_manager_db_update_duration_seconds"
    min: 0
    max: 1.0
  - name: "user_manager_db_update_duration_seconds"
    query: "total_user"
    min: 0
    max: 10.0
  - name: "cpu_usage_high_user_manager"
    query: "user_manager_cpu_usage_percent"
    min: 0
    max: 10
  - name: "deduplication_cache_size_high_user_manager"
    query: "deduplication_cache_size"
    min: 0
    max: 10
  - name: "last_update_delay_data_collector"
    query: "time()-last_successful_update_timestamp"
    min: 0
    max: 30